pub const Flags = packed struct(u32) {
    key_press: bool = false,
    key_release: bool = false,
    button_press: bool = false,
    button_release: bool = false,
    enter_window: bool = false,
    leave_window: bool = false,
    pointer_motion: bool = false,
    pointer_motion_hint: bool = false,
    button1_motion: bool = false,
    button2_motion: bool = false,
    button3_motion: bool = false,
    button4_motion: bool = false,
    button5_motion: bool = false,
    button_motion: bool = false,
    keymap_state: bool = false,
    exposure: bool = false,
    visibility_change: bool = false,
    structure_notify: bool = false,
    resize_redirect: bool = false,
    substructure_notify: bool = false,
    substructure_redirect: bool = false,
    focus_change: bool = false,
    property_change: bool = false,
    colormap_change: bool = false,
    owner_grab_button: bool = false,
    /// Unused and must be zeroed
    _pad: u7 = 0,
};

pub const mask_values = struct {
    pub const key_press: u32 = 1 << 0;
    pub const key_release: u32 = 1 << 1;
    pub const button_press: u32 = 1 << 2;
    pub const button_release: u32 = 1 << 3;
    pub const enter_window: u32 = 1 << 4;
    pub const leave_window: u32 = 1 << 5;
    pub const pointer_motion: u32 = 1 << 6;
    pub const pointer_motion_hint: u32 = 1 << 7;
    pub const button1_motion: u32 = 1 << 8;
    pub const button2_motion: u32 = 1 << 9;
    pub const button3_motion: u32 = 1 << 10;
    pub const button4_motion: u32 = 1 << 11;
    pub const button5_motion: u32 = 1 << 12;
    pub const button_motion: u32 = 1 << 13;
    pub const keymap_state: u32 = 1 << 14;
    pub const exposure: u32 = 1 << 15;
    pub const visibility_change: u32 = 1 << 16;
    pub const structure_notify: u32 = 1 << 17;
    pub const resize_redirect: u32 = 1 << 18;
    pub const substructure_notify: u32 = 1 << 19;
    pub const substructure_redirect: u32 = 1 << 20;
    pub const focus_change: u32 = 1 << 21;
    pub const property_change: u32 = 1 << 22;
    pub const colormap_change: u32 = 1 << 23;
    pub const owner_grab_button: u32 = 1 << 24;
    pub const _pad: u32 = 0x7f << 25;
};
